// Generated by CoffeeScript 1.10.0
(function() {
  var browsersync, del, gulp, nodemon, rename, runsequence;

  gulp = require('gulp');

  nodemon = require('gulp-nodemon');

  del = require('del');

  runsequence = require('run-sequence');

  browsersync = require('browser-sync');

  rename = require('gulp-rename');

  gulp.task('default', function(callback) {
    return runsequence(['clean'], ['develop'], ['browsync', 'watch'], callback);
  });

  gulp.task('clean', function(callback) {
    console.log('this is a clean task!....................');
    return callback();
  });

  gulp.task('miniJS', function() {
    return console.log('this is miniJS task.............');
  });

  gulp.task('miniCoffee', function() {
    return console.log('copy coffe files.............');
  });

  gulp.task('miniCSS', function() {
    return console.log('this is miniCSS task.............');
  });

  gulp.task('miniHTML', function() {
    return console.log('this is miniHTML task.............');
  });

  gulp.task('build', function(callback) {
    return runsequence(['clean'], ['miniJS', 'miniCSS', 'miniHTML', 'miniCoffee'], callback);
  });

  gulp.task('develop', function(callback) {
    nodemon({
      script: 'bin/www',
      ext: 'js ejs coffee html',
      tasks: ['build']
    });
    return callback();
  });

  gulp.task('browsync', function() {
    return browsersync({
      proxy: 'http://localhost:3000',
      port: 8800,
      notify: true
    });
  });

  gulp.task('watch', function() {
    return gulp.watch(['./routes/**/*.*', './spiders/**/*.*', './views/**/*.*', './public/**/*.*'], ['reload']);
  });

  gulp.task('reload', function(callback) {
    return runsequence(['bsreload'], callback);
  });

  gulp.task('bsreload', function() {
    return browsersync.reload();
  });

}).call(this);
