// Generated by CoffeeScript 1.10.0
(function() {
  var browsersync, del, gulp, nodemon, runsequence, sass;

  gulp = require('gulp');

  nodemon = require('gulp-nodemon');

  sass = require('gulp-ruby-sass');

  del = require('del');

  runsequence = require('run-sequence');

  browsersync = require('browser-sync');

  gulp.task('default', function(callback) {
    return runsequence(['clean'], ['develop'], ['browsync', 'watch'], callback);
  });

  gulp.task('clean', function(callback) {
    console.log('this is a clean task!....................');
    return callback();
  });

  gulp.task('miniJS', function() {
    return console.log('this is miniJS task.............');
  });

  gulp.task('miniCSS', function() {
    return console.log('this is miniCSS task.............');
  });

  gulp.task('miniHTML', function() {
    return console.log('this is miniHTML task.............');
  });

  gulp.task('build', function(callback) {
    return runsequence(['miniJS', 'miniCSS', 'miniHTML'], callback);
  });

  gulp.task('develop', function() {
    return nodemon({
      script: 'bin/www',
      ext: 'js ejs coffee html',
      tasks: ['build']
    });
  });

  gulp.task('browsync', function() {
    return browsersync({
      proxy: 'localhost:8800'
    });
  });

  gulp.task('watch', function() {
    return gulp.watch(['./../*.{css,js,ejs,coffee}'], 'reload');
  });

  gulp.task('reload', function(callback) {
    return runsequence(['develop'], ['browsync'], ['bsreload'], callback);
  });

  gulp.task('bsreload', function() {
    return browsersync.reload();
  });

}).call(this);
