// Generated by CoffeeScript 1.10.0
(function() {
  var express, real, router, sapi;

  express = require('express');

  router = express.Router();

  real = require('../spiders/api');

  sapi = require('../spiders/sapi');

  router.get('/', function(req, res) {
    return res.render('index', {
      title: 'Express'
    });
  });

  router.get('/api', function(req, res) {
    var r;
    r = new real('http://www.cbooo.cn/');
    return r.getData(res);
  });

  router.get('/sapi', function(req, res) {
    var s;
    s = new sapi('http://www.cbooo.cn/Screen/getScreenData?days=0');
    return s.getData(res);
  });

  module.exports = router;

}).call(this);
