// Generated by CoffeeScript 1.10.0
(function() {
  var express, real, router, sapi, ttrapi, tvapi;

  express = require('express');

  router = express.Router();

  real = require('../spiders/api');

  sapi = require('../spiders/sapi');

  ttrapi = require('../spiders/ttrapi');

  tvapi = require('../spiders/tvapi');

  router.get('/', function(req, res) {
    return res.render('index', {
      title: 'Express'
    });
  });

  router.get('/api', function(req, res) {
    var r;
    r = new real('http://www.cbooo.cn/');
    return r.getData(res);
  });

  router.get('/sapi', function(req, res) {
    var s;
    s = new sapi('http://www.cbooo.cn/Screen/getScreenData?days=0');
    return s.getData(res);
  });

  router.get('/ttrapi', function(req, res) {
    var ttr;
    ttr = new ttrapi('http://www.cbooo.cn/Screen/getTrendScreenData');
    return ttr.getData(res);
  });

  router.get('/tvapi', function(req, res) {
    var tv;
    tv = new tvapi('http://www.cbooo.cn/Mess/getDayPlays?tvType=1');
    return tv.getData(res);
  });

  module.exports = router;

}).call(this);
