// Generated by CoffeeScript 1.10.0
(function() {
  var express, paipian, router;

  express = require('express');

  router = express.Router();

  paipian = require('../spiders/paipian');

  router.get('/', function(req, res) {
    var pp;
    pp = new paipian('http://www.cbooo.cn/Screen/getScreenData?days=0');
    return pp.getData(res);
  });

  module.exports = router;

}).call(this);
