// Generated by CoffeeScript 1.10.0
(function() {
  var express, realt, router;

  express = require('express');

  router = express.Router();

  realt = require('../spiders/real');

  router.get('/', function(req, res) {
    var rt;
    rt = new realt('http://www.cbooo.cn/');
    return rt.getData(res);
  });

  module.exports = router;

}).call(this);
