// Generated by CoffeeScript 1.10.0
(function() {
  var cheerio, real, superagent;

  superagent = require('superagent');

  cheerio = require('cheerio');

  real = function(url) {
    return this.url = url;
  };

  real.prototype = {
    getData: function(response) {
      return superagent.get(this.url).end(function(err, res) {
        var $, all, films, grade, img, imgs;
        if (err) {
          return console.error(err);
        } else {
          all = [];
          films = [];
          imgs = [];
          $ = cheerio.load(res.text);
          img = '';
          grade = '';
          $('#topdatatr tr').each(function() {
            if ($(this).find('td:nth-child(8)').children().length > 0) {
              img = 'http://www.cbooo.cn' + $(this).find('td:nth-child(8) img').attr('src').trim();
              grade = $(this).find('td:nth-child(8)').text().trim();
            }
            return films.push({
              id: $(this).attr('id'),
              order: $(this).find('td:nth-child(1)').text(),
              name: $(this).find('td:nth-child(2)').text(),
              ptime: $(this).find('td:nth-child(3)').text(),
              rate: $(this).find('td:nth-child(4)').text(),
              pall: $(this).find('td:nth-child(5)').text(),
              prate: $(this).find('td:nth-child(6)').text(),
              days: $(this).find('td:nth-child(7)').text(),
              img: {
                isup: img,
                grade: grade
              }
            });
          });
          $('#dvBannerRight dl').each(function() {
            return imgs.push({
              id: $(this).attr('id').trim().substring(indexOf('_')),
              img: $(this).find('dt span img').attr('src').trim()
            });
          });
          all.push({
            films: films,
            imgs: imgs
          });
          return response.send(all);
        }
      });
    }
  };

  module.exports = real;

}).call(this);
